'use strict';


var reasonReactBlue = "#48a9dc";

var style = "\n  *{\n    padding: 0px;\n    margin: 0px;\n    font-family: system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Ubuntu, \"Helvetica Neue\", sans-serif;\n  }\n  input:focus,\nselect:focus,\ntextarea:focus,\nbutton:focus {\n    outline: none;\n}\n  body {\n    background-color: #fff;\n  }\n  .app {\n    display: flex;\n  }\n  .red {\n    height: 200px;\n    background-color: red;\n  }\n  .green {\n    height: 200px;\n    background-color: green;\n  }\n  .col{\n    display: flex;\n    flex-direction: column;\n  }\n  .col-3 {\n    display: flex;\n    flex-direction: column;\n    width: 24.99%;\n  }\n  .col-4 {\n    display: flex;\n    flex-direction: column;\n    width: 33.32%;\n  }\n  .col-5 {\n    display: flex;\n    flex-direction: column;\n    width: 41.65%;\n  }\n  .row {\n    display: flex;\n    flex-direction: row;\n  }\n  .border-right {\n    border-right: 1px solid #ccc;\n  }\n  .border-left {\n    border-left: 1px solid #ccc;\n  }\n  button {\n    background-color: rgba(29,161,242,1.00);\n    color: #fff;\n    font-size: 0.9rem;\n    font-weight: bold;\n    border: none;\n    border-radius: 20px;\n    padding: 8px 17px;\n  }\n  .postHeader {\n    margin-bottom: 20px;\n  }\n  .postHeader__title {\n    padding: 10px;\n    border: 1px solid #ccc;\n    border-right: none;\n    border-left: none;\n  }\n  .postHeader__title > h3 {\n    font-weight: bold;\n    line-height: 1.3125;\n\n  }\n  .postHeader__content {\n    padding: 10px;\n  }\n  .postHeader__profile {\n    width: 50px;\n    height: 50px;\n    border-radius: 50px;\n  }\n  .postHeader__input {\n    width: 100%;\n    margin: 10px;\n    border: none;\n    font-size: 1.05rem;\n  }\n  .postHeader__footer {\n    display:flex;\n    justify-content: flex-end;\n    padding: 10px;\n    border-bottom: 1px solid #ccc;\n  }\n  .post {\n    padding: 5px;\n    border: 1px solid #ccc;\n    border-left: none;\n    border-right: none;\n  }\n  .post__image {\n\n  }\n  .post__user__info {\n    padding: 5px;\n  }\n  .post__user__info > h3 {\n    font-size: 0.95rem;\n  }\n  .post__user__info > p {\n    font-size: 0.94rem;\n    color: rgba(0,0,0,0.5);\n    margin: 0px 0.5rem;\n  }\n  .post__content {\n    padding: 5px;\n  }\n";

exports.reasonReactBlue = reasonReactBlue;
exports.style = style;
/* No side effect */
